### ISSUE TITLE
[Bug]: The game crashes when join the world

### ISSUE THREAD

**Issue by Edrig** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#11]
### Minecraft Version

1.19.2

### Mod Loader and Version

Forge-43.2.3

### Ad Astra! Version

1.11.9

### Addon Mod Version (This Mod)

forge-1.19.2-1.7

### The details

the game crashes when you join the world

https://crashy.net/leP5iuf0Vb2RGHkpsTvQ
https://bytebin.lucko.me/ypwGucb1Dn

**Comment by gisellevonbingen** [comment]
Ok i had success for reproduce.
Some mods looks conflict with this mod.

**Comment by gisellevonbingen** [comment]
Fixed version is released. Try check it.
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4311970
