### ISSUE TITLE
[Bug]: Fuel Loader right click

### ISSUE THREAD

**Issue by Edrig** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#12]
### Minecraft Version

1.19.2

### Mod Loader and Version

Forge-43.2.3

### Ad Astra! Version

1.11.9

### Addon Mod Version (This Mod)

forge-1.19.2-1.8

### The details

1. Place a Fuel Loader
2. Right Click the Fuel Loader
3. the game disconnect server and send this crash report 

https://crashy.net/INPLZDSWLjML4MHHU3jw
https://bytebin.lucko.me/r2Pqv3X01q

**Comment by gisellevonbingen** [comment]
I think this problem is from REI compatibilities.
Can you send report to REI dev first? 
I will fix when If they says it is not REI's fault.

**Comment by shedaniel** [comment]
This is not REI's fault as the class is not a part of the JEI API spec. Use another way to get the gui pos, the JEI internals way is not the way.
Alternatively you can enable the Forge REI integration and disable the REI's JEI compat layer by following https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/23#issuecomment-1332489186

**Comment by gisellevonbingen** [comment]
> This is not REI's fault as the class is not a part of the JEI API spec. Use another way to get the gui pos, the JEI internals way is not the way. Alternatively you can enable the Forge REI integration and disable the REI's JEI compat layer by following [shedaniel/REIPluginCompatibilities-Issues#23 (comment)](https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/23#issuecomment-1332489186)

Ah yes, it was not api spec. ok I see.
Thanks for fast feedback

**Comment by gisellevonbingen** [comment]
Fixed at 5c672ea5f85299d8d71bbd9cac40bee90768963e
Next version will work normally.
Waiting for review from CurseForge now.

**Comment by gisellevonbingen** [comment]
Released https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4313623
Try check it.
