### ISSUE TITLE
[Bug]: Fuel Loader doesn't maintain fluid on dedicated server restart

### ISSUE THREAD

**Issue by Sebastrn** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#13]
### Minecraft Version

1.19.2

### Mod Loader and Version

Forge-43.2.3

### Ad Astra! Version

1.12.1

### Addon Mod Version (This Mod)

1.9

### The details

Hello!

I was testing the mod in my dedicated server and noticed that if the server restarts, the fluid tank in the fuel loader resets to 0. This doesn't happen is a player disconnects or is the chunks are not loaded.

**Comment by gisellevonbingen** [comment]
It problem looks cause dependency mod "Botarium".
I'll report to Botarium Devs.
Thanks for report!
