### ISSUE TITLE
[Bug]: Oxygen can doesn't work when set to Charge Armor or Charge Inventory

### ISSUE THREAD

**Issue by Sebastrn** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#14]
### Minecraft Version

1.19.2

### Mod Loader and Version

Forge-43.2.3

### Ad Astra! Version

1.12.1

### Addon Mod Version (This Mod)

1.9

### The details

If I have a normal Oxygen Can full with oxygen and change it to Charge Armor or Charge Inventory, the Oxygen Can empties but it doesn't charge the Space Suit with oxygen.

I tested this in a dedicated server.

**Comment by gisellevonbingen** [comment]
I checked it working now.
Did you test on venus or mercury?
There need 'Netherite Oxygen Can'
Check tempurator range in tooltip

**Comment by gisellevonbingen** [comment]
Reopen if you have problem still.

**Comment by Old-Man-D** [comment]
I just experienced this same behavior in ATM8.  I am in lunar orbit space station, setting the regular oxygen cans to fill my armor just makes them drain immediately
