### ISSUE TITLE
[Feature]: freeze prevention

### ISSUE THREAD

**Issue by ggrgg13** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#16]
### Request details

An upgrade & enchantment that protects against freezing would be nice.

**Comment by gisellevonbingen** [comment]
'Space Breathing' can prevent freeze

**Comment by ggrgg13** [comment]
Hmm it wasn't working for me. Let me test it some more and come back.

**Comment by gisellevonbingen** [comment]
Did you tried on Ad Astra!'s planet ?

**Comment by ggrgg13** [comment]
Tried it at Earth orbit. Mekanism upgrade working, Pneumaticcraft one does not work.

**Comment by ggrgg13** [comment]
Nvm I was being stupid, didn't turn on the upgrade
was off by default

**Comment by gisellevonbingen** [comment]
It's ok.
Have fun!
