### ISSUE TITLE
[Bug]: Helmets unbreakable by default can't receive "Space Breathing" enchantment

### ISSUE THREAD

**Issue by James103** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#19]
### Minecraft Version

1.19.2

### Mod Loader and Version

Forge 43.2.3

### Ad Astra! Version

1.12.2

### Addon Mod Version (This Mod)

1.10

### The details

Originally reproduced in modpack "All the Mods 8" version 1.0.10. See also https://github.com/AllTheMods/ATM-8/issues/865

When attempting to apply the "Space Breathing" enchantment onto a helmet, if that helmet is not a vanilla helmet and is unbreakable by default, it is very likely the enchantment won't be compatible with the helmet.

For example, if the "Allthemodium" mod is installed, the Allthemodium Helmet from that mod can't receive the enchantment.

To reproduce:
1. Install the mentioned mods.
2. Install mods that add new armor sets and helmets, such as Allthemodium, Mystical Agriculture, and Deeper and Darker.
3. Run `enchant @s ad_astra_giselle_addon:space_breathing` while holding various modded helmets in your hand.
4. Take note as to whether the enchantment is compatible or not.

**Comment by gisellevonbingen** [comment]
OK, I now know why.
ATM's armors has special property.
I'll release patched version soon.

**Comment by gisellevonbingen** [comment]
Fixed in 1.12 version
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4392563

try check
