### ISSUE TITLE
[Feature]: Missing tags, Thermals Sawmill recipes

### ISSUE THREAD

**Issue by shal0l** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#20]
### Cause for request

All of the ad astra tree planks have minecraft:planks, but the wooden construction blocks lack the wooden tags. The "logs" lack thermal series sawmill recipes. I would request specific planet stone tags to make it easier to hide them in REI (I don't know JavaScript!) but there is no incentive to do it..
I noticed you've done some fixes to tags too, so maybe you can also include them in the [Ad Astra Repository](https://github.com/terrarium-earth/Ad-Astra). Thanks!

### Request details

`ad_astra:glacian_log` `ad_astra:stripped_glacian_log` `ad_astra:aeronos_stem` `ad_astra:aeronos_cap` `ad_astra:strophar_stem` `ad_astra:strophar_cap` as thermal sawmill recipes for planks

`#minecraft:logs_that_burn` to `ad_astra:glacian_log` and `ad_astra:stripped_glacian_log` Item tags

Add `#minecraft:wooden_slabs` Item tags to 
ad_astra:aeronos_slab
ad_astra:strophar_slab
ad_astra:glacian_slab

`#minecraft:wooden_stairs`
ad_astra:aeronos_stairs
ad_astra:glacian_stairs
ad_astra:strophar_stairs

`#minecraft:wooden_fences #forge:fences #forge:fences/wooden`
ad_astra:aeronos_fence
ad_astra:strophar_fence
ad_astra:glacian_fence

`#forge:chests #forge:chests/wooden` - Item and block tags
ad_astra:aeronos_chest
ad_astra:strophar_chest

Sidenote, all of these items besides the plank blocks aren't burnable in furnaces.

**Comment by gisellevonbingen** [comment]
Great. i was don't realize that before you talk to me.
Missing tags will added from Ad-Astra

**Comment by gisellevonbingen** [comment]
Sawmill recipes remained.

**Comment by gisellevonbingen** [comment]
Sawmill recipes added
