### ISSUE TITLE
[Feature]: Make the Mekanism fuels compatible 

### ISSUE THREAD

**Issue by tankyap** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#21]
### Cause for request

In Mekanism mod theres 2 kinds of fuel I believe: one is Biofuel and one is Fissile fuel(which is a bit expensive to make). It seems those recipes for those fuels didn't appear on the JEI menu.

### Request details

Just add a fuel compatible with this addon from two of those fuels from Mekanism. Shouldn't be too hard...

**Comment by gisellevonbingen** [comment]
### Bio Fuel

Umm... Ad-Astra! is only accept fuel as fluid tagged ad_astra:fuel.
Bio Fuel it is item, So need a special way for make it to fluid.
No way right now in mekanism and Ad-Astra! and this mod.

Maybe it would be solve through add 'Bio Fuel' fluid and 'Fluidizer' machine.
But considering balance and compatibility with other mods,
I don't want add them right now.

### Fissile Fuel

It is too.
No way make it to fluid in mekanism yet.

### Fianlly

Is you modpack developer?
Then, I recommend add new recipe what make biofuel to fluid via KubeJS or CraftTweaker.
In else, should install other mod what added bio fuel/diesel.
Like Thermal Expansion or Immersive Engineering.

Thanks for idea but sorry i didn't implement it.
