### ISSUE TITLE
[Bug]: Space Fire Proof Unit for Meka-Suit not working

### ISSUE THREAD

**Issue by selkiess** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#22]
### Minecraft Version

1.19.2

### Mod Loader and Version

43.2.6

### Ad Astra! Version

1.12.3

### Addon Mod Version (This Mod)

1.12

### The details

Hello,
Been going through this mod in ATM8 and it would seem the "Space Fire Proof Unit" does not work with the mekanism meka suit.
I can put it on the suit but once entering mercury or venus i just immediately start dying.
Space breathing/gravity both work fine,
Thanks

**Comment by gisellevonbingen** [comment]
Did you have just 'Oxygen Can'?, not 'Netherite Oxygen Can'.

**Comment by gisellevonbingen** [comment]
In my test, it work fine.

Need 'Netherite Oxygen Can' in hot planet.
Check temperature range in tooltip on oxygen can.

![image](https://user-images.githubusercontent.com/44163945/226362631-d62feb8c-ee7c-4a3e-a97e-3493f4d72508.png)
![image](https://user-images.githubusercontent.com/44163945/226362972-4db02491-16f0-4725-9875-bbf30158cf4a.png)
![image](https://user-images.githubusercontent.com/44163945/226362686-00649c99-99b1-4bb5-8a24-4fe8b593762a.png)

**Comment by selkiess** [comment]
> In my test, it work fine.
> 
> Need 'Netherite Oxygen Can' in hot planet. Check temperature range in tooltip on oxygen can.
> 
> ![image](https://user-images.githubusercontent.com/44163945/226362631-d62feb8c-ee7c-4a3e-a97e-3493f4d72508.png) ![image](https://user-images.githubusercontent.com/44163945/226362972-4db02491-16f0-4725-9875-bbf30158cf4a.png) ![image](https://user-images.githubusercontent.com/44163945/226362686-00649c99-99b1-4bb5-8a24-4fe8b593762a.png)

I am a moron, completely missed the temperature range, just assumed the netherite ones were just higher capacity.
Thanks!

**Comment by gisellevonbingen** [comment]
you are not bad.
Have fun!
