### ISSUE TITLE
[Feature]: Polish version

### ISSUE THREAD

**Issue by malezjaa** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#23]
### Request details

Hi, I can translate the mod into Polish.

**Comment by gisellevonbingen** [comment]
That's good.
Can you upload translation file here or create a pull request?
Original lang file is here https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon/blob/1.19.2/common/src/main/resources/assets/ad_astra_giselle_addon/lang/en_us.json

**Comment by malezjaa** [comment]
https://pastebin.com/QNcFYA5m It's a finished version.

**Comment by gisellevonbingen** [comment]
whole versions released what added polski translation.
try check it out
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files

**Comment by malezjaa** [comment]
Thank you so much!
