### ISSUE TITLE
[Feature]: Add oxygen tank unit for mekanism bodyarmor

### ISSUE THREAD

**Issue by zyxkad** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#24]
### Cause for request

Carry a small nether tank is not enough, I want if I can leave in the space for longer time and use less inventory.

### Request details

Add a tank unit which can carry ton of oxygen for the breathing unit

**Comment by gisellevonbingen** [comment]
A similar attempt was made a long time ago,
But Mekanism's API not support its,
So I replaced it with another way.

**Comment by gisellevonbingen** [comment]
Instead, I can suggest these .
1. Change oxygen can's capacity in config.
2. Store oxygen can in unused curios slots in right now.

**Comment by zyxkad** [comment]
Well, nvm, I can use pneumaticCraft interface to auto refill empty tank, that works too
