### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fartunrus** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#28]
### Minecraft Version

1.19.2

### Mod Loader and Version

Forge-43.2.0

### Ad Astra! Version

1.12.6

### Addon Mod Version (This Mod)

1.8

### The details

1. I install an addon to a mod and I get an error Ad Astra!L Giselle Addon (ad_astra_giselle_addon) encountered an error during the sided_setup event phase
java.lang.NoClassDefFoundError: earth/terrarium/ad_astra/client/ClientUtils$ScreenConstructor
2. https://pastebin.com/w7dhvKYU
3. As you can see from the report, only Ad Astra and the addon are installed

**Comment by gisellevonbingen** [comment]
Update addon mod to latest.
Should use latest version if Ad astra updated.
