### ISSUE TITLE
Simplified Chinese language package key bug fix

### ISSUE THREAD

**Issue by shenyx110** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#30]
### The details

Simplified Chinese language package key bug fix
[ad-addon.zip](https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon/files/11512992/ad-addon.zip)

The previous version was missing a comma.

**Comment by gisellevonbingen** [comment]
It's ok.
I was fixed.

Thanks for review
