### ISSUE TITLE
[Bug]: Hopper or shift click will put the oxygen can to the water slot, but not the oxygen slot

### ISSUE THREAD

**Issue by zyxkad** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#34]
### Minecraft Version

1.19.2

### Mod Loader and Version

forge-43.2.14

### Ad Astra! Version

1.12.6

### Addon Mod Version (This Mod)

1.16

### The details

1. place a oxygen loader

Opt1:

2. place a hopper toward to the loader
3. put a oxygen can into the hopper

Opt2:

2. get a oxygen can
3. open the loader's GUI, and shift click the can

---

4. The oxygen can will be transfer to the water slot

**Comment by gisellevonbingen** [comment]
Hopper  transfer and gui shift click are implemented by Ad Astra.
So sadly, addon mod can't solve this issue.
