### ISSUE TITLE
[Bug]: Crash when booting game only sometimes? (pneumaticcraft compat issue?)

### ISSUE THREAD

**Issue by Gbergz** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#35]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge 47.1.0

### Ad Astra! Version

1.15.1

### Addon Mod Version (This Mod)

5.1

### The details

1. Install Ad Astra
2. Install Giselle Addon
3. Have pneumaticcraft installed.
4. Boot game.
5. Crash.
profit.

Crash-report: https://gist.githubusercontent.com/Gbergz/c57081d1016d03ea0b31c79d915fe7ee/raw/5b9661c0917c62dda41c315c3798d0a5645642f2/gistfile1.txt

Note: It's a weird one because this only happens on some systems, even then not always.

**Comment by gisellevonbingen** [comment]
Mod loading order is looks weired.

**Comment by Gbergz** [comment]
Something that I can do about that myself or is this your doing?

**Comment by gisellevonbingen** [comment]
I failed to reproduce it. but found candidate to fix.
Can you test with new version(5.2)?

https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4630415

**Comment by Gbergz** [comment]
Seems to have fixed it for people who tested.

**Comment by gisellevonbingen** [comment]
OK good, thanks for report.
