### ISSUE TITLE
[Feature]: 𝓛𝓲𝓯𝓮 𝓼𝓾𝓹𝓹𝓸𝓻𝓽 𝓼𝔂𝓼𝓽𝓮𝓶𝓼 w/ Pollution of the realms

### ISSUE THREAD

**Issue by TishinaVC** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#36]
### Cause for request

Pollution of the realms support for oxygen generation and air quality concerns

### Request details

Pollution of the realms support so a fire on your station is actually a big problem choosing between venting the pollution along with some air by cracking a hole into your base walls or using a pollution filter as a scrubber.    

you can set O2 to dissipate at a y level above the build height of the space dimension you are in just like the pollution on the overworld so it can be safely assumed it has leaked out of your base or station

you could generate O2 in the same gas block way of pollution of the realms. without being in contact with O2 gas blocks in the base you'd need a tank or suffocate ya know.

**Comment by gisellevonbingen** [comment]
Can you suggest this to 'Pollution of the realms' first?
They implemented many compatibility with other mods.
