### ISSUE TITLE
mod on Modrinth?

### ISSUE THREAD

**Issue by ColonelGerdauf** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#37]
### The details

I feel that it would make sense if this addon mod existed on Modrinth as well as Curseforge, as Ad Astra already is in Modrinth, so it would be easier for users if the addon was found alongside the base mod.

**Comment by gisellevonbingen** [comment]
That makes sense.
Created (Under review now)
https://modrinth.com/mod/ad-astra-giselle-addon
