### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sharkweekthings** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#38]
### Minecraft Version

1.19.2

### Mod Loader and Version

43.2.21

### Ad Astra! Version

ad_astra-forge-1.19.2-1.12.7

### Addon Mod Version (This Mod)

1.19.2.1.16

### The details

![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/134178249/07020378-2ae8-42eb-acf1-bb2655f6da69)

This morning I woke up to a few of my server packs getting rejected for whats shown in the screenshot above.  Any ideas? 

These are older uploads, so I am not sure what it's trying to suggest :o

**Comment by sharkweekthings** [comment]
![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/134178249/e5279039-5e4e-477e-9437-adaf2a3df246)

Looks like my most recent server file got rejected as well for the same reason D:

**Comment by gisellevonbingen** [comment]
There is no code that can cause problems in this mod.
Would you like to contact to curseforge support team literally?
Or upload the file to here what you uploaded on the modpack here.

**Comment by sharkweekthings** [comment]
[Ad-Astra-Giselle-Addon-forge-1.19.2-1.16.zip](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/files/12229017/Ad-Astra-Giselle-Addon-forge-1.19.2-1.16.zip)

Here is the mod, am just using version Ad-Astra-Giselle-Addon-forge-1.19.2-1.16 // no weirdness, for that matter, not even using any datapacks for your mod. 

No idea why Curseforge is being sucha pain.

**Comment by gisellevonbingen** [comment]
No abnormalities were found with your file.
I guess you have to contact to Curseforge support team.

**Comment by sharkweekthings** [comment]
They must be having issues on their end or something.. This happened recently: 

![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/134178249/344b4daa-a9a6-4ba2-8c88-edfe49e567c8)

Everything is now being RE-Re scanned.. lol.. 

Thank you for your time. I am glad nothing is wrong with your mod (I didnt think there was) I just wanted to let you know that Curseforge was being weird and flagging it for something. 

Hopefully after this next pass through, the server pack for my pack will get posted.. haha.
