### ISSUE TITLE
[Bug]: Space Breathing Enchantment Doesn't Work

### ISSUE THREAD

**Issue by TheMCSpacePro** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#39]
### Minecraft Version

1.20.1

### Mod Loader and Version

NeoForge 47.1.65

### Ad Astra! Version

1.15.3

### Addon Mod Version (This Mod)

5.2

### The details

When attempting to use the **Space Breathing** enchantment alongside the required Oxygen Can item, I still end up dying from asphyxiation, though the oxygen can is still used. Doesn't matter if it's in my inventory or a Curios slot, the game still kills me from no oxygen.

https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/53196852/4a90d4de-51eb-40d8-9de5-0b2a6c44bd6d

**Comment by gisellevonbingen** [comment]
Weird.. never did this before...
It seems to only happen on newer versions of Forge.

**Comment by TheMCSpacePro** [comment]
Argh... that's annoying. Does that mean it's something not easily fixable?

**Comment by gisellevonbingen** [comment]
Changed SpaceBreathing's operation triggers. 0e0e100d3a2093b5ea8e8ca0fcd9d0640c7b48fe
I will test and release soon.

**Comment by gisellevonbingen** [comment]
New version released.
https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4694772
