### ISSUE TITLE
Minecraft crashes if Mekanism is not installed

### ISSUE THREAD

**Issue by Sebastrn** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#4]
Hello,

The game crashes when Mekanism is not installed even when Mekanism is an optional dependency

Minecraft Version:
1.19.2

Forge Version:
43.2.0

Giselle Addon Version:
1.3

You can see the crash report here:
https://pastebin.com/0B497sFT

**Comment by gisellevonbingen** [comment]
Thanks for report.
Will fix next version
