### ISSUE TITLE
Mekanism 1.20

### ISSUE THREAD

**Issue by brix02** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#46]
### The details

Hi, I am using mekanism 1.20 (new version from github), but I cant see your unit upgrades in JEI. Your mod is installed correctly cause i can see other items from your mod like enchanted books, cans and etc... but not the mekasuit upgrades where could be a problem?

**Comment by gisellevonbingen** [comment]
As you known mekanism is not official released at 1.20.
So, removed mekanism compatibility items, codes for now.
Please wait for mekanism released.

**Comment by gisellevonbingen** [comment]
I will comment to here when mekanism compatibility re-added.

**Comment by brix02** [comment]
Alright thanks

**Comment by gisellevonbingen** [comment]
Released
1. https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4777024
2. https://modrinth.com/mod/ad-astra-giselle-addon/version/5.7
