### ISSUE TITLE
[Bug]: PneumaticCraft space breathing doesn't allow breathing in water

### ISSUE THREAD

**Issue by AP1028** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#48]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge-47.1.3

### Ad Astra! Version

1.15.3

### Addon Mod Version (This Mod)

5.6

### The details

1. Wear pneumatic armor with space breathing installed and enabled, with oxygen cans.
3. Jump into water.
![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/105597219/a0aecc9a-857e-47da-a70c-d5cd53999434)
I guess this is just not added because pneumatic armor has the SCUBA upgrade, but with the stock ad astra space suit, it is possible to breathe underwater with oxygen tanks. It makes no sense that something that can breathe in space cannot breathe in water.

**Comment by gisellevonbingen** [comment]
ok, i know now ad-astra was implement it as intent.
i will add function to use pnc air to fill player with air

**Comment by gisellevonbingen** [comment]
OK it added.
NEED oxygen can in inventory or curios slots.
https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4819646
