### ISSUE TITLE
Minecraft crashes when Applied Energistics 2 Wireless Terminals installed

### ISSUE THREAD

**Issue by Sebastrn** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#5]
Game doesn't start and no crash-report is generated

Minecraft Version:
1.19.2

Forge Version:
43.2.0

Giselle Addon Version:
1.3

[Applied Energistics 2 Wireless Terminals](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals) Version:
12.8.4

Log:
https://pastebin.com/ERZ5fXtp

**Comment by gisellevonbingen** [comment]
Thanks for report
i'm started finding cause and will comment after fix this.

**Comment by gisellevonbingen** [comment]
Fixed at 1.4 (https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4181188)
