### ISSUE TITLE
[Feature]: Rocket loading and sending

### ISSUE THREAD

**Issue by BlackSand87** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#50]
### Cause for request

Automatically Loading items into rockets and launching them would be cool for automation

### Request details

Add a block to load items into the rocket.

For launching either its possible to make another block that triggers launch on redstone or make the launchpad accept redstone and on a full 15 redstone strength launch the rocket.

**Comment by gisellevonbingen** [comment]
I think it can add a that function to rocket sensor.
However, player must be on ride just before launch, and the set to destination and landing process must be manually performed.
Because Ad Astra does not provide features to automate them.

**Comment by gisellevonbingen** [comment]
If you don't mind, please ask to Ad Astra Devs for implement that function to Rework Version.
If they accept, that will be added in 1.20 and be more sophisticated and powerful.

**Comment by BlackSand87** [comment]
Alr, I'll put suggest it on the ad astra github in the next few days ty
