### ISSUE TITLE
[Bug]: It crashes on startup

### ISSUE THREAD

**Issue by TheMade4** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#51]
### Minecraft Version

1.20.1

### Mod Loader and Version

Fabric-0.15.3

### Ad Astra! Version

1.15.8

### Addon Mod Version (This Mod)

5.6

### The details

1. I install Ad Astra, Ad Astra: Giselle Addon, and the necessary libraries. Then I start the game and the game crashes.
2. https://pastebin.com/gDwxbqVz
3. This may be due to an outdated version of the "Ad Astra: Giselle Addon" for Fabric.

**Comment by TheMade4** [comment]
oh... I used the alpha version of Ad Astra which came out in January of this year...

**Comment by charliez0** [comment]
same issues here, but an update would be better!
