### ISSUE TITLE
[Bug]: Immediate crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#52]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge - 47.2.19

### Ad Astra! Version

1.15.10

### Addon Mod Version (This Mod)

6.3

### The details

Install latest version of Giselle Addon, instant crash on startup. No crash report is created to provide. Minimal information in log. Was only able to discover this mod was the issue by rolling back recent updates.

Providing with those logs to see if anything in them helps at all.

[latest](https://gist.github.com/DelviousCrafts/9614a9470c49ebd33c3f3ff802f41f24)
[debug](https://gist.github.com/DelviousCrafts/6b0c8f77f773cbdc21585fc130852892)

**Comment by gisellevonbingen** [comment]
Oops. i was uploaded not final file.
Fixed with 6.4 version
https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/5047970
