### ISSUE TITLE
[Feature]: Compatibility with Create Netherite Diving suit

### ISSUE THREAD

**Issue by DaddySpin** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#53]
### Cause for request

The Create Netherite Diving suit has a backtank filled with air and it allows you to breath underwater. it would be cool if you had the helmet or chestplate enchanted with the spacing breathing enchant that it would use the backtanks air and not take durability damage.

**Comment by gisellevonbingen** [comment]
Done.
Applied will to next version.

**Comment by DaddySpin** [comment]
Does this require you to wear the full suit to count or only the helmet and backtank?

**Comment by gisellevonbingen** [comment]
Backtank is can be used like oxygen can.
No need to equip Backtank in Ad Astra dimension.

You just need to equip 'Space Breathing' enchanted any helmet.
Then use pressured air automatically.

**Comment by DaddySpin** [comment]
Ah I see so all you need is a backtank and space breathing. Is it possible to have an optional setting to require a full netherite diving suit to be in space?

**Comment by gisellevonbingen** [comment]
This is unavoidable due to the way Space Breathing works.
There are currently no plans.

**Comment by DaddySpin** [comment]
Fair enough, well I got my create compat so I'm happy thanks!
