### ISSUE TITLE
[Error Loading]: Mekanism: Weapons (mekaweapons) encountered an error during the enqueue_imc event phase

### ISSUE THREAD

**Issue by Null-Ification** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#55]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge-47.2.0

### Ad Astra! Version

1.15.16

### Addon Mod Version (This Mod)

6.4

### The details

![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/154444578/79fb888f-8c86-4545-a0d6-4f137768fb7e)
my guess here is that your code tries to put space breathing unit into any meka-related thing except for meka-tool (for shorter code)
and meka-weapon is not for breathing in space.
that's just my guess, I sent the crash log when you needed it.

**Comment by Null-Ification** [comment]
darn it

**Comment by gisellevonbingen** [comment]
Is it ok if remove mekanism: weapons?
I need crash report.

**Comment by gisellevonbingen** [comment]
I can't reproduce.
Send me crash report.

**Comment by gisellevonbingen** [comment]
Try update Mekanism: Weapons omeranha/MekaWeapons#10
