### ISSUE TITLE
[Feature]: Respect Unbreaking in Enchantments

### ISSUE THREAD

**Issue by peri-anth** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#59]
### Cause for request

As can be seen [here](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/blob/b2eba76bbbd98e69f7b8b480c5b17cd04b351fec/common/src/main/java/ad_astra_giselle_addon/common/item/ItemUsableResource.java#L35), the mod's enchantments set the durability of armor instead of actually damaging the item. This means that unbreaking on the item is ignored, and as a consequence, armor enchanted with the mod's enchantments breaks quickly.

### Request details

Instead of setting the durability of armor enchanted with the mod's enchantments, do damage the same way as other enchants (thorns, soul speed, ...), which will respect the unbreaking enchantment.

**Comment by gisellevonbingen** [comment]
That makes sense.
I will fix it

**Comment by gisellevonbingen** [comment]
Patched at 1.19.2, 1.20.1, 1.20.4.
Thanks for suggestion.
