### ISSUE TITLE
[Bug]: Game won't load

### ISSUE THREAD

**Issue by vizthex123** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#60]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge 47.2.6

### Ad Astra! Version

1.15.18

### Addon Mod Version (This Mod)

1.5.8

### The details

I get this screen error when trying to load the game with the add-on installed
![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/31721920/041cc89b-b420-496d-8049-482d9d832cf3)

Log:
[latest.log](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/files/15440307/latest.log)

**Comment by gisellevonbingen** [comment]
Update to latest version please. https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/5310246

**Comment by vizthex123** [comment]
> Update to latest version please. https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/5310246

would be nice if it was marked as a release to prevent this from happening in the future.
