### ISSUE TITLE
[Feature]: Display Oxygen status with Mekasuit / otherr armours with Space breathing Module / Enchant

### ISSUE THREAD

**Issue by MissCatTrap** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#61]
### Cause for request

At present, its very easy to die when you run out of Oxygen because you do not get a GUI displaying your oxygen tank status unlike the Ad Astra Space Suit / Netherite Space Suit / Jet Suit.

### Request details

When you have armour with Space Breathing capabilities (MekaSuit Unit / Enchant) display the Ad Astra GUI for your Oxygen Status to prevent unwanted / unexpected player deaths.

**Comment by gisellevonbingen** [comment]
Mekasuit is already have hud.

![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/44163945/4195da66-0ce3-415d-94d2-993ad9279aaf)
![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/44163945/faa8b0e2-60fc-4792-b1a1-d3a6f25935a8)

**Comment by MissCatTrap** [comment]
I was about to post a picture saying I don't have it, but I didn't realise it's disabled by default. Might be worth changing it as I can't see why you *wouldnt* want to know by default if you're installing it. Thanks!

**Comment by gisellevonbingen** [comment]
I will add oxygen tank gui overlay when equipped Space Breathing enchanted helment.
