### ISSUE TITLE
[Bug]: 1.20.1 forge Crashes with ad astra giselle addon

### ISSUE THREAD

**Issue by Alisa121212** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#63]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge 47.2.20

### Ad Astra! Version

1.15.5

### Addon Mod Version (This Mod)

6.8

### The details

So i just start my minecraft and my game crashes, crash report didn't loads but i have latest log. Without this mod all works fine and loads. 

Latest log - https://pastebin.com/i1e2RqpL
list of installed mods: 
![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/52006485/793d8588-28cc-40d3-98c0-64877c327ae5)

![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/52006485/a1c1d253-baa1-4ec3-be45-76a0f379afb2)

![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/52006485/c2791aa4-316f-4842-8dd3-b9d6e6ff8a0f)

**Comment by gisellevonbingen** [comment]
The log says:
```
[19:57:12] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'ad_astra', Requested by: 'ad_astra_giselle_addon', Expected range: '[1.15.18,)', Actual version: '1.15.5'
```
Please update Ad Astra.
Else downgrade this mod.
