### ISSUE TITLE
[Feature]:  Allow the fuel loader to load fuels that don't have the #ad_astra:fuel tag but do have #ad_astra:tier_x_rocket_fuel

### ISSUE THREAD

**Issue by casmin7** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#64]
### Cause for request

Right now any tier of rocket can use any fuel by giving it the specific tag, but the fuel loader only works if said fluid also had the fuel tag. Issue is that the #fuel tag has all of the other tags as children and cannot be modified until the #fuel tag is removed from the liquid.

Sorry for the bad english, I'm not from an anglophone country.

**Comment by gisellevonbingen** [comment]
That is great point. I was missed that 'specific fuel tags'.
Fuel Loader will be changed to give fluid what matching with Vehicle's specific tag.

But for easy distinguish, i think fluids are need 'adastra:fuel' tag at least.

**Comment by gisellevonbingen** [comment]
Done e59f033e8ab970c59f946b7c2976e61620776308.

**Comment by souldbminerr** [comment]
The fuel loader on 6.13 can still load fuel into rockets which cannot accept the tiered fuel. The fuel does not get used in the T2 rocket. With the fuel loader, it can be loaded
![image](https://github.com/user-attachments/assets/9cf136ac-7698-45c9-86f3-b4a42ddfe119)
![image](https://github.com/user-attachments/assets/cac8ab21-22f1-447a-bd33-27af24fc6f95)
