### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by kwkotopai** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#67]
### Cause for request

Doesnt have gravity in items that i drop or are dropped and neither on entities like mobs.

### Request details

The gravity normalizer is a great machine but i think it misses one thing, a function that enables gravity for items and entities too

**Comment by gisellevonbingen** [comment]
Applied to 1.19.2-1.22 and 1.20.1-6.10 versions.

Thanks for idea!
