### ISSUE TITLE
[Bug]: Crash opening fuel loader with latest JEI

### ISSUE THREAD

**Issue by evhub** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#68]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge 47.3.0

### Ad Astra! Version

1.15.18

### Addon Mod Version (This Mod)

6.11

### The details

With JEI 15.8.0.16, opening the fuel loader causes this client crash: https://bytebin.lucko.me/q4FkpSDgos

**Comment by gisellevonbingen** [comment]
Fixed, Thanks for report!
