### ISSUE TITLE
[Bug]: the compatibility with mekasuit 

### ISSUE THREAD

**Issue by Buzzspaceranger** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#69]
### Minecraft Version

1.20.4

### Mod Loader and Version

Neoforge

### The details

[message (1).txt](https://github.com/user-attachments/files/16675763/message.1.txt)
Help?

**Comment by gisellevonbingen** [comment]
OK, i will fix it soon.

**Comment by gisellevonbingen** [comment]
Fixed. https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/5647179
Thanks for report!
