### ISSUE TITLE
[Feature]: Fuel blacklist

### ISSUE THREAD

**Issue by denisJaved** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#71]
### Cause for request

Tag `#forge:fuel` commonly used so a lot different fluids tagged like this. But not every fluid shoud be used as rocket fuel.

### Request details

New tag (for example `#forge:fuel/no_rocket_use`) can be added. Fluids tagged like this can't be used in fuel loader.
Or this feature can be adde through mod config. Or even kubeJS support can be added.

But in my opinion tag solution is best.

PS: You can't just remove fluid from `#forge:fuel` tag becouse this can break other mods

**Comment by gisellevonbingen** [comment]
You can do that already modifying `'tier_N_rocket_fuel'` fluid tags.
https://github.com/terrarium-earth/Ad-Astra/tree/1.20.1/common/src/main/generated/resources/data/ad_astra/tags/fluids

[Ad-Astra/common/src/main/generated/resources/data/ad_astra/tags/fluids/tier_1_rocket_fuel.json](https://github.com/terrarium-earth/Ad-Astra/blob/1.20.1/common/src/main/generated/resources/data/ad_astra/tags/fluids/tier_1_rocket_fuel.json)
```json
{
  "values": [
    "#ad_astra:fuel"
  ]
}
```
Try remove '#ad_astra:fuel' element and customize.
