### ISSUE TITLE
[Bug]: Crashing Fuel Loaer

### ISSUE THREAD

**Issue by NecroxEye** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#73]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge 47.3.12-1.20.1

### Ad Astra! Version

1.15.19

### Addon Mod Version (This Mod)

6.15

### The details

1. Got Fuel Loader
2. Placed Fuel loader near rockets 
3. Server crashed
4. Cant join back untill took out the mod

**Comment by gisellevonbingen** [comment]
Can't reproduce when Ad Astra and this mod only installed.
Please upload crashreport.

**Comment by xiaojuzi122** [comment]
I'm in a similar situation, but I have Dandi2k8's Ad Extendra additionally installed[https://modrinth.com/mod/ad_extendra-continuation](url)

**Comment by xiaojuzi122** [comment]
This is the output of my server:
[latest.log](https://github.com/user-attachments/files/18020488/latest.log)
