### ISSUE TITLE
can't install space fire proof unit on mekasuit

### ISSUE THREAD

**Issue by tawan256** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#9]
### The details

space fire proof unit didn't has any compatible armor pieces, did you forget to add it?

**Comment by gisellevonbingen** [comment]
Oh god. I missed it.
Next version will release soon with fix this.
Thanks for report.

**Comment by gisellevonbingen** [comment]
Try check it
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4306597
